- name: Install Docker
  hosts: ["client", "gpu", "milvus"]
  tags: ["client", "gpu", "milvus"]
  connection: ssh
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['ca-certificates', 'curl']
        state: present

    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update

    - name: Install Docker and related packages
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
        state: present

    - name: Test Docker
      command: docker run hello-world
    
- name: Install Milvus
  hosts: ["milvus"]
  tags: ["milvus"]
  connection: ssh
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Download Milvus standalone script
      get_url:
        url: https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh
        dest: /home/ubuntu/standalone_embed.sh
        mode: '0755'

    - name: Start Milvus standalone
      command: bash /home/ubuntu/standalone_embed.sh start

- name: Deploy benchmark
  hosts: ["client", "gpu"]
  tags: ["client", "gpu"]
  connection: ssh
  remote_user: ubuntu
  tasks:
    - name: Copy scripts folder
      copy:
        src: ../streamsense/
        dest: /home/ubuntu/video-stream-indexing/streamsense/
        directory_mode: 0755
        owner: ubuntu
    - name: Copy benchmarks folder
      copy:
        src: ../benchmarks/
        dest: /home/ubuntu/video-stream-indexing/benchmarks/
        directory_mode: 0755
        owner: ubuntu
    
- name: Client specific tasks
  hosts: ["client"]
  tags: ["client"]
  connection: ssh
  remote_user: ubuntu
  tasks:    
    - name: Copy video folder
      copy:
        src: ../videos/
        dest: /home/ubuntu/video-stream-indexing/videos/
        directory_mode: 0755
        owner: ubuntu
    - name: Install AWS CLI
      become: yes
      command: snap install aws-cli --classic

    # - name: Download dataset
      # command: aws s3 cp s3://video-indexing-data/ /home/ubuntu/video-stream-indexing/videos/ --recursive

- name: GPU specific tasks
  hosts: ["gpu"]
  tags: ["gpu"]
  connection: ssh
  remote_user: ubuntu
  tasks:    
    - name: Create results directory
      file:
        path: /home/ubuntu/video-stream-indexing/results/
        state: directory
        mode: '0755'
        owner: ubuntu




- name: Pull Docker image
  hosts: ["client", "gpu"]
  tags: ["client", "gpu"]
  connection: ssh
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Pull Docker image using bash command
      command: docker pull arnaugabriel/video-indexing:2.0

    - template:
        src: "templates/constants.py"
        dest: "/home/ubuntu/video-stream-indexing/streamsense/policies/constants.py"


